# Generated by Django 3.1.4 on 2020-12-27 03:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_item_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Menu item id.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the menu item.', max_length=100)),
                ('description', models.TextField(default=None, help_text='Menu item description.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the menu is available.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('menu_items', models.ManyToManyField(blank=True, related_name='menu', to='foodadmin.MenuItem')),
            ],
        ),
    ]
