# Generated by Django 3.1.4 on 2020-12-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='MENU_ITEM',
        ),
    ]
