# Generated by Django 3.1.4 on 2020-12-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodadmin', '0002_auto_20201227_0058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_item',
        ),
    ]
