# Generated by Django 3.1.4 on 2020-12-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodadmin', '0003_auto_20201227_0102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_items',
        ),
    ]
