# Generated by Django 3.1.4 on 2020-12-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodadmin', '0004_auto_20201227_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
    ]
