# Generated by Django 3.1.4 on 2020-12-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='EMPLOYEE',
        ),
    ]
