# Generated by Django 3.1.4 on 2020-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=models.EmailField(help_text='Email of the employee.', max_length=254, unique=True), help_text='Employee username.', max_length=100),
        ),
    ]
