# Generated by Django 3.1.4 on 2020-12-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20201227_1746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees_',
        ),
    ]
