# Generated by Django 3.1.4 on 2020-12-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20201227_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
