# Generated by Django 3.1.4 on 2020-12-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20201227_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
