# Generated by Django 3.1.4 on 2020-12-27 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_auto_20201227_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Employee id.', primary_key=True, serialize=False),
        ),
    ]
