# Generated by Django 3.1.4 on 2020-12-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_delete_menucustomizations'),
        ('employees', '0017_auto_20201227_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
