# Generated by Django 3.1.4 on 2020-12-27 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_remove_employee_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Menu id.', primary_key=True, serialize=False)),
                ('menu_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the menu is available.')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('menu_option_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Menu item id.', primary_key=True, serialize=False)),
                ('option', models.CharField(help_text='Menu option number.', max_length=50, null=True)),
                ('menu_items', models.CharField(help_text='Menu items separated by comma.', max_length=500, null=True)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='MenuCustomizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_text', models.CharField(help_text='Employee customizations', max_length=500, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu')),
            ],
            options={
                'db_table': 'menu_customizations',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_options',
            field=models.ForeignKey(help_text='Options in the menu', on_delete=django.db.models.deletion.CASCADE, to='menus.menuoptions'),
        ),
    ]
