# Generated by Django 3.1.4 on 2020-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_options',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_1',
            field=models.CharField(help_text='Option 1 in the menu', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_2',
            field=models.CharField(help_text='Option 2 in the menu', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_3',
            field=models.CharField(help_text='Option 3 in the menu', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_4',
            field=models.CharField(help_text='Option 4 in the menu', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_5',
            field=models.CharField(help_text='Option 5 in the menu', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='MenuOptions',
        ),
    ]
