# Generated by Django 3.1.4 on 2020-12-28 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time when selection was modified.', null=True)),
                ('option_selected', models.CharField(blank=True, help_text='Option selected by the employee.', max_length=500, null=True)),
                ('customization_notes', models.CharField(blank=True, help_text='Customization notes', max_length=500, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu')),
            ],
            options={
                'db_table': 'menu_employees',
            },
        ),
    ]
