# Generated by Django 3.1.4 on 2020-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20201227_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_option_1',
            field=models.CharField(blank=True, help_text='Option 1 in the menu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_option_2',
            field=models.CharField(blank=True, help_text='Option 2 in the menu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_option_3',
            field=models.CharField(blank=True, help_text='Option 3 in the menu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_option_4',
            field=models.CharField(blank=True, help_text='Option 4 in the menu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_option_5',
            field=models.CharField(blank=True, help_text='Option 5 in the menu', max_length=300, null=True),
        ),
    ]
