# Generated by Django 3.1.4 on 2020-12-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20201227_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_option_1',
            field=models.CharField(help_text='Option 1 in the menu', max_length=300, null=True),
        ),
    ]
