# Generated by Django 3.1.4 on 2020-12-27 11:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20201227_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Is menu confirmed.'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default=uuid.uuid4, help_text='Menu Name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date the menu is available.'),
        ),
    ]
