# Generated by Django 3.1.4 on 2020-12-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20201227_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default="Today's menu", help_text='Menu Name.', max_length=100),
        ),
    ]
