# Generated by Django 3.1.4 on 2020-12-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20201227_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCustomizations',
        ),
    ]
