# Generated by Django 3.1.4 on 2020-12-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_menucustomizations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCustomizations',
        ),
    ]
