# Generated by Django 3.1.4 on 2020-12-28 00:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Menu id.', primary_key=True, serialize=False)),
                ('menu_name', models.CharField(default="Today's menu", help_text='Menu Name.', max_length=100)),
                ('menu_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Menu available date.')),
                ('menu_option_1', models.CharField(help_text='Option 1 in the menu', max_length=300, null=True)),
                ('menu_option_2', models.CharField(blank=True, help_text='Option 2 in the menu', max_length=300, null=True)),
                ('menu_option_3', models.CharField(blank=True, help_text='Option 3 in the menu', max_length=300, null=True)),
                ('menu_option_4', models.CharField(blank=True, help_text='Option 4 in the menu', max_length=300, null=True)),
                ('menu_option_5', models.CharField(blank=True, help_text='Option 5 in the menu', max_length=300, null=True)),
                ('menu_option_6', models.CharField(blank=True, help_text='Option 6 in the menu', max_length=300, null=True)),
                ('menu_option_7', models.CharField(blank=True, help_text='Option 7 in the menu', max_length=300, null=True)),
                ('menu_option_8', models.CharField(blank=True, help_text='Option 8 in the menu', max_length=300, null=True)),
                ('menu_option_9', models.CharField(blank=True, help_text='Option 9 in the menu', max_length=300, null=True)),
                ('menu_option_10', models.CharField(blank=True, help_text='Option 10 in the menu', max_length=300, null=True)),
                ('is_confirmed', models.BooleanField(default=True, help_text='Is menu confirmed.')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
