# Generated by Django 3.1.4 on 2020-12-27 03:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Employee id.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First name of the employee.', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the employee.', max_length=100)),
                ('email', models.EmailField(help_text='Email of the employee.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Password of the employee.', max_length=50)),
                ('is_admin', models.BooleanField(default=False, help_text='If the employee is admin.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the employee was created.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date when the employee was modified.')),
            ],
        ),
    ]
