# Generated by Django 3.1.4 on 2020-12-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201227_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(help_text='Employee username.', max_length=50, null=True),
        ),
    ]
