# Generated by Django 3.1.4 on 2020-12-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Password of the employee.', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(help_text='Employee username.', max_length=100, null=True),
        ),
    ]
